const COUNTRY_CODES = {
  Algeria: "DZ",
  Angola: "AO",
  Argentina: "AR",
  Australia: "AU",
  Belgium: "BE",
  Brazil: "BR",
  Bulgaria: "BG",
  Cameroon: "CM",
  Canada: "CA",
  Chile: "CL",
  China: "CN",
  Colombia: "CO",
  "Costa Rica": "CR",
  Croatia: "HR",
  "Czech Republic": "CZ",
  "DR Congo": "CD",
  Denmark: "DK",
  Ecuador: "EC",
  Egypt: "EG",
  France: "FR",
  Gabon: "GA",
  Georgia: "GE",
  Germany: "DE",
  Ghana: "GH",
  Greece: "GR",
  Guinea: "GN",
  Haiti: "HT",
  Hungary: "HU",
  Iceland: "IS",
  Iran: "IR",
  Ireland: "IE",
  Israel: "IL",
  Italy: "IT",
  "Ivory Coast": "CI",
  Japan: "JP",
  Liberia: "LR",
  Mali: "ML",
  Mexico: "MX",
  Montenegro: "ME",
  Morocco: "MA",
  Netherlands: "NL",
  Nigeria: "NG",
  Norway: "NO",
  Paraguay: "PY",
  Poland: "PL",
  Portugal: "PT",
  Romania: "RO",
  "Saudi Arabia": "SA",
  Senegal: "SN",
  Serbia: "RS",
  "Sierra Leone": "SL",
  Slovakia: "SK",
  Slovenia: "SI",
  "South Africa": "ZA",
  "South Korea": "KR",
  Spain: "ES",
  Sweden: "SE",
  Switzerland: "CH",
  Togo: "TG",
  Tunisia: "TN",
  Turkey: "TR",
  USA: "US",
  Ukraine: "UA",
  Uruguay: "UY",
  Venezuela: "VE",
  England: "gb-eng",
  Wales: "gb-wls",
  "Northern Ireland": "gb-nir",
  "Soviet Union": "",
};

// Returns the local flag image path for a nation (e.g. "/flags/gr.png"),
// or "" when no flag is available. Image flags are used instead of emoji so
// they render identically on every OS and browser (Windows/Firefox render
// regional-indicator emoji as bare letters).
export function countryFlagPath(nation) {
  if (!nation) return "";
  const code = COUNTRY_CODES[nation];
  if (!code) return "";
  return `/flags/${code.toLowerCase()}.png`;
}
